program Archivar;

{$R *.dres}

uses
  ShareMem,
  Vcl.Forms,
  {$ifdef RELEASE}
  JclAppInst,
  {$endif }
  u_eventHandler in 'Events\u_eventHandler.pas',
  u_ini in 'misc\u_ini.pas',
  m_glob_client in 'm_glob_client.pas' {GM: TDataModule},
  f_main in 'f_main.pas' {MainForm},
  u_stub in 'u_stub.pas',
  f_gremiumForm in 'Gremium\f_gremiumForm.pas' {GremiumForm},
  u_misc in 'u_misc.pas',
  f_gremium_edit in 'Gremium\f_gremium_edit.pas' {GremiumEditForm},
  f_personen in 'Personen\f_personen.pas' {PersonenForm},
  f_person_edit in 'Personen\f_person_edit.pas' {PersonEditForm},
  f_gremium_MA_form in 'Gremium\f_gremium_MA_form.pas' {GremiumMAForm},
  f_task_new in 'Task\f_task_new.pas' {Taskform},
  fr_file in 'File\fr_file.pas' {FileFrame: TFrame},
  fr_task_head in 'Task\fr_task_head.pas' {TaskHeaderFrame: TFrame},
  f_taskEdit in 'Task\f_taskEdit.pas' {TaskEditForm},
  fr_gremiumTree in 'misc\fr_gremiumTree.pas' {GremiumTreeFrame: TFrame},
  u_gremium in 'Gremium\u_gremium.pas',
  fr_taskList in 'Task\fr_taskList.pas' {TaskListFrame: TFrame},
  m_WindowHandler in 'misc\m_WindowHandler.pas' {WindowHandler: TDataModule},
  u_json in '..\misc\u_json.pas',
  xsd_data in '..\misc\xsd_data.pas',
  u_addInfo in 'misc\u_addInfo.pas',
  f_uploadForm in 'File\f_uploadForm.pas' {UploadForm},
  f_gremiumList in 'Gremium\f_gremiumList.pas' {GremiumListForm},
  u_Konst in '..\misc\u_Konst.pas',
  u_lockInfo in '..\misc\u_lockInfo.pas',
  f_bechlus in 'Beschlus\f_bechlus.pas' {Beschlusform},
  f_protokoll in 'Protokoll\f_protokoll.pas' {ProtokollForm},
  f_protokoll_list in 'Protokoll\f_protokoll_list.pas' {ProtocollListForm},
  u_bookmarkList in 'bookmarks\u_bookmarkList.pas',
  u_bookmark in 'bookmarks\u_bookmark.pas',
  m_BookMarkHandler in 'bookmarks\m_BookMarkHandler.pas' {BookMarkHandler: TDataModule},
  f_images in 'images\f_images.pas' {ImagesForm},
  fr_bookmark in 'bookmarks\fr_bookmark.pas' {BookmarkFrame: TFrame},
  u_berTypes in '..\misc\u_berTypes.pas',
  f_taksListForm in 'Task\f_taksListForm.pas' {TaskListForm},
  xsd_protocol in '..\misc\xsd_protocol.pas',
  f_titel_edit in 'Protokoll\f_titel_edit.pas' {TitelEditform},
  fr_chapter in 'Protokoll\fr_chapter.pas' {ChapterFrame: TFrame},
  xsd_chapter in '..\misc\xsd_chapter.pas',
  f_chapterEdit in 'Protokoll\f_chapterEdit.pas' {ChapterEditForm},
  fr_taskList2 in 'Task\fr_taskList2.pas' {TaskList2Frame: TFrame},
  u_taskEntry in 'Task\u_taskEntry.pas',
  f_chapter_content in 'Protokoll\f_chapter_content.pas' {ChapterContentForm},
  f_datafields in 'Datafields\f_datafields.pas' {DataFieldForm},
  f_datafield_edit in 'Datafields\f_datafield_edit.pas' {DatafieldEditform},
  i_datafields in 'Datafields\i_datafields.pas',
  u_PropertyImpl in 'Datafields\u_PropertyImpl.pas',
  u_DataFieldImpl in 'Datafields\u_DataFieldImpl.pas',
  u_DataFieldLislImpl in 'Datafields\u_DataFieldLislImpl.pas',
  f_taskEditor in 'TaskEditor\Forms\f_taskEditor.pas' {TaksEditorForm},
  i_taskEdit in 'TaskEditor\i_taskEdit.pas',
  u_TaskImpl in 'TaskEditor\u_TaskImpl.pas',
  f_tableField_editor in 'TaskEditor\Forms\f_tableField_editor.pas' {TableFieldEditorForm},
  u_DataField2XML in 'Datafields\u_DataField2XML.pas',
  u_TaskDataField2XML in 'TaskEditor\Writer\u_TaskDataField2XML.pas',
  u_Task2XML in 'TaskEditor\Writer\u_Task2XML.pas',
  fr_Formeditor in 'TaskEditor\Forms\fr_Formeditor.pas' {EditorFrame: TFrame},
  u_TaskFormImpl in 'TaskEditor\u_TaskFormImpl.pas',
  u_TaskCtrlImpl in 'TaskEditor\u_TaskCtrlImpl.pas',
  u_TaskCtrlPropImpl in 'TaskEditor\u_TaskCtrlPropImpl.pas',
  fr_propertyEditor in 'TaskEditor\Forms\fr_propertyEditor.pas' {PropertyFrame: TFrame},
  u_TaskControlFactory in 'TaskEditor\controls\u_TaskControlFactory.pas',
  u_TaskCtrlLabel in 'TaskEditor\controls\u_TaskCtrlLabel.pas',
  u_TaskCtrlEdit in 'TaskEditor\controls\u_TaskCtrlEdit.pas',
  u_TaskCtrlGroupBox in 'TaskEditor\controls\u_TaskCtrlGroupBox.pas',
  u_TaskCtrlLabeledEdit in 'TaskEditor\controls\u_TaskCtrlLabeledEdit.pas',
  u_TaskCtrlTable in 'TaskEditor\controls\u_TaskCtrlTable.pas',
  u_TaskCtrlComboBox in 'TaskEditor\controls\u_TaskCtrlComboBox.pas',
  u_typeHelper in 'misc\u_typeHelper.pas',
  f_itemsEditor in 'TaskEditor\PropEdits\f_itemsEditor.pas' {ItemsEditorForm},
  f_tableColumns in 'TaskEditor\Forms\f_tableColumns.pas' {TableColumnsForm},
  f_table_Column in 'TaskEditor\Forms\f_table_Column.pas' {TableCloumnForm},
  u_TaskCtrlTableField in 'TaskEditor\controls\u_TaskCtrlTableField.pas',
  u_taskForm2XML in 'TaskEditor\Writer\u_taskForm2XML.pas',
  f_testform in 'TaskEditor\Forms\f_testform.pas' {TestForm},
  u_helper in '..\misc\u_helper.pas',
  fr_report in 'TaskEditor\Forms\fr_report.pas' {ReportFrame: TFrame},
  f_form_props in 'TaskEditor\Forms\f_form_props.pas' {FormProperties},
  u_TaskCtrlPanel in 'TaskEditor\controls\u_TaskCtrlPanel.pas',
  u_TaskCtrlMemo in 'TaskEditor\controls\u_TaskCtrlMemo.pas',
  u_TaskCtrlRichEdit in 'TaskEditor\controls\u_TaskCtrlRichEdit.pas',
  u_TaskCtrlSpliter in 'TaskEditor\controls\u_TaskCtrlSpliter.pas',
  f_itemsTStringsEditor in 'TaskEditor\PropEdits\f_itemsTStringsEditor.pas' {StringEditorForm},
  m_http in 'http\m_http.pas' {HttpMod: TDataModule},
  m_html in 'http\m_html.pas' {HtmlMod: TDataModule},
  u_TTaskFileImpl in 'TaskEditor\u_TTaskFileImpl.pas',
  u_TTaskContainerImpl in 'TaskEditor\u_TTaskContainerImpl.pas',
  u_TTaskStylesImpl in 'TaskEditor\u_TTaskStylesImpl.pas',
  u_tTaskStyleImpl in 'TaskEditor\u_tTaskStyleImpl.pas',
  u_TTaskFilesImpl in 'TaskEditor\u_TTaskFilesImpl.pas',
  f_InputBox in 'misc\f_InputBox.pas' {InputBoxForm},
  f_selectList in 'misc\f_selectList.pas' {SelectListform},
  m_dws in 'dws\m_dws.pas' {DwsMod: TDataModule},
  u_zipHelper in 'misc\u_zipHelper.pas',
  f_template_new in 'Templates\f_template_new.pas' {TemplateNewForm},
  f_select_templateForm in 'Templates\f_select_templateForm.pas' {SelectTemplateForm},
  f_task_datafields in 'TaskEditor\f_task_datafields.pas' {TaskDatafieldsForm},
  f_df_EnumList in 'Datafields\Editor\f_df_EnumList.pas' {DFEnumListForm},
  f_df_listbox in 'Datafields\Editor\f_df_listbox.pas' {ListBoxForm},
  i_personen in 'Personen\i_personen.pas',
  u_PersonImpl in 'Personen\u_PersonImpl.pas',
  u_PersonenListeImpl in 'Personen\u_PersonenListeImpl.pas',
  i_beschluss in 'Beschlus\i_beschluss.pas',
  u_AbstimmungImpl in 'Beschlus\u_AbstimmungImpl.pas',
  u_BeschlussImpl in 'Beschlus\u_BeschlussImpl.pas',
  xsd_DataField in '..\misc\xsd_DataField.pas',
  f_set in 'misc\f_set.pas' {MySettingsForm},
  f_textblock_edit in 'TextBlock\f_textblock_edit.pas' {TextBlockEditForm},
  fr_form in 'TaskEditor\fr_form.pas' {FormFrame: TFrame},
  f_chapterTask in 'Protokoll\f_chapterTask.pas' {ChapterTaskForm},
  xsd_Styles in '..\misc\xsd_Styles.pas',
  fr_ReportEditor in 'TaskEditor\Forms\fr_ReportEditor.pas' {ReportFrameEditor: TFrame},
  fr_ReportEditor_html in 'TaskEditor\Forms\fr_ReportEditor_html.pas' {ReportFrameEditorHtml: TFrame},
  fr_ReportEditor_pas in 'TaskEditor\Forms\fr_ReportEditor_pas.pas' {ReportFrameEditorPas: TFrame},
  fr_ReportEditor_img in 'TaskEditor\Forms\fr_ReportEditor_img.pas' {ReportFrameEditorImg: TFrame},
  i_chapter in 'Protokoll\i_chapter.pas',
  u_ChapterImpl in 'Protokoll\u_ChapterImpl.pas',
  u_ChapterListImpl in 'Protokoll\u_ChapterListImpl.pas',
  u_ChapterTitleListImpl in 'Protokoll\u_ChapterTitleListImpl.pas',
  u_ChapterTitleImpl in 'Protokoll\u_ChapterTitleImpl.pas',
  u_ProtocolImpl in 'Protokoll\u_ProtocolImpl.pas',
  u_speedbutton in 'misc\u_speedbutton.pas',
  f_testblock_list in 'TextBlock\f_testblock_list.pas' {TestBlockListForm},
  f_textblock_param in 'TextBlock\f_textblock_param.pas' {TextBlockParameterForm},
  m_taskLoader in 'Task\m_taskLoader.pas' {TaskLoaderMod: TDataModule},
  m_cache in 'File\m_cache.pas' {CacheMod: TDataModule},
  f_webserver_files in 'http\f_webserver_files.pas' {WebServerFilesForm},
  f_web_file in 'http\f_web_file.pas' {WebFileForm},
  u_BeschlussListeImpl in 'Beschlus\u_BeschlussListeImpl.pas',
  m_protocol in 'Protokoll\m_protocol.pas' {ProtocolMod: TDataModule},
  u_teilnehmerImpl in 'Protokoll\u_teilnehmerImpl.pas',
  u_TTeilnehmerListeImpl in 'Protokoll\u_TTeilnehmerListeImpl.pas',
  f_abwesenheit in 'Protokoll\f_abwesenheit.pas' {AbwesenForm},
  u_BesucherImpl in 'Protokoll\u_BesucherImpl.pas',
  u_BesucherlisteImpl in 'Protokoll\u_BesucherlisteImpl.pas',
  f_besucher in 'Protokoll\f_besucher.pas' {BesucherForm},
  u_templateCache in 'Task\u_templateCache.pas' {TemplateCacheMod: TDataModule},
  u_renderer in 'Protokoll\u_renderer.pas',
  f_protokoll_view in 'Protokoll\f_protokoll_view.pas' {ProtokollViewForm},
  u_protocoll2XML in 'Protokoll\u_protocoll2XML.pas',
  f_web_editor in 'http\f_web_editor.pas' {WebEditorForm},
  f_epub in 'ePub\f_epub.pas' {epubform},
  f_epub_mngr in 'ePub\f_epub_mngr.pas' {epubMngrForm},
  fr_epub in 'ePub\fr_epub.pas' {ePupFrame: TFrame},
  f_downloadEpub in 'ePub\f_downloadEpub.pas' {DownloadEpubform},
  f_meeting_new in 'Sitzung\f_meeting_new.pas' {MeetingForm},
  f_task_filter in 'Task\f_task_filter.pas' {TaskFilterForm},
  fr_to in 'Sitzung\fr_to.pas' {TOFrame: TFrame},
  f_meeting_select in 'Sitzung\f_meeting_select.pas' {SelectMeetingForm},
  f_meeting_proto in 'Sitzung\f_meeting_proto.pas' {MeetingProtoForm},
  f_login in 'misc\f_login.pas' {LoginForm},
  fr_meeting in 'Sitzung\fr_meeting.pas' {MeetingFrame: TFrame},
  u_teilnehmer in '..\misc\u_teilnehmer.pas',
  f_protocol_sec in 'Protokoll\f_protocol_sec.pas' {ProtocolSectionForm},
  u_kategorie in 'Task\u_kategorie.pas',
  u_onlineUser in 'misc\u_onlineUser.pas',
  f_meeting_person in 'Sitzung\f_meeting_person.pas' {MeetingPersonForm},
  f_doMeeting in 'Sitzung2\f_doMeeting.pas' {DoMeetingform},
  fr_teilnehmer in 'Sitzung\fr_teilnehmer.pas' {TNFrame: TFrame},
  fr_protocol in 'Protokoll\fr_protocol.pas' {ProtocolFrame: TFrame},
  fr_MeetingTN in 'Sitzung2\fr_MeetingTN.pas' {MeetingTNFrame: TFrame},
  fr_beschluss in 'Beschlus\fr_beschluss.pas' {BeschlussFrame: TFrame},
  f_abstimmung in 'Online\f_abstimmung.pas' {AbstimmungsForm},
  f_image_preview in 'images\f_image_preview.pas' {ImagePreviewform},
  f_textblock_preview in 'TextBlock\f_textblock_preview.pas' {TextBlockPreviewForm},
  xsd_TextBlock in '..\misc\xsd_TextBlock.pas',
  u_ePub in '..\misc\ePub\u_ePub.pas',
  u_navpoint in '..\misc\ePub\u_navpoint.pas',
  u_xml in '..\misc\ePub\u_xml.pas',
  f_task_type in 'Task\f_task_type.pas' {TaskTypeForm},
  m_fileCache in 'File\m_fileCache.pas' {FileCacheMod: TDataModule},
  f_flieCacheForm in 'File\f_flieCacheForm.pas' {FileCacheForm},
  f_fileuploadform in 'File\f_fileuploadform.pas' {FileUploadForm},
  fr_log in 'Task\fr_log.pas' {LogFrame: TFrame},
  f_log_entry in 'Task\f_log_entry.pas' {LogEntryform},
  f_taglist in 'TextBlock\f_taglist.pas' {TagListForm},
  m_crypt in '..\misc\m_crypt.pas' {CryptMod: TDataModule},
  f_keys in 'crypt\f_keys.pas' {Keysform},
  f_textblock_export in 'TextBlock\f_textblock_export.pas' {TextBlockExportForm},
  f_textblock_import in 'TextBlock\f_textblock_import.pas' {TextblockImportForm},
  u_taskCtrlRadio in 'TaskEditor\controls\u_taskCtrlRadio.pas',
  u_TaskCtrlCheck in 'TaskEditor\controls\u_TaskCtrlCheck.pas',
  u_TaskCtrlRadioGroup in 'TaskEditor\controls\u_TaskCtrlRadioGroup.pas',
  u_ValidatorFactory in 'TaskEditor\Validator\u_ValidatorFactory.pas',
  u_ValidatorStringImpl in 'TaskEditor\Validator\u_ValidatorStringImpl.pas',
  u_ValidatorBoolImpl in 'TaskEditor\Validator\u_ValidatorBoolImpl.pas',
  u_validatorBaseImpl in 'TaskEditor\Validator\u_validatorBaseImpl.pas',
  u_validatorIntegerImpl in 'TaskEditor\Validator\u_validatorIntegerImpl.pas',
  u_ValidatorFloatImpl in 'TaskEditor\Validator\u_ValidatorFloatImpl.pas',
  u_ValidatorDateTimeImpl in 'TaskEditor\Validator\u_ValidatorDateTimeImpl.pas',
  u_ValidatorEnumImpl in 'TaskEditor\Validator\u_ValidatorEnumImpl.pas',
  u_taskCtrlDateTimePicker in 'TaskEditor\controls\u_taskCtrlDateTimePicker.pas',
  f_storage in 'dms\f_storage.pas' {StorageForm},
  f_file_info in 'dws\f_file_info.pas' {FileInfoForm},
  fr_storages in 'dms\fr_storages.pas' {StoragesFrame: TFrame},
  f_storages in 'dms\f_storages.pas' {StoragesForm},
  f_personen_list in 'Personen\f_personen_list.pas' {PersonenListForm},
  CodeSiteLogging {PersonenListForm},
  f_protokoll_new in 'Protokoll\f_protokoll_new.pas' {ProtokollNewForm},
  fr_gremium in 'Gremium\fr_gremium.pas' {GremiumFrame: TFrame},
  xsd_Task in '..\misc\xsd_Task.pas',
  u_ShowMessageTimeOut in 'misc\u_ShowMessageTimeOut.pas',
  f_admin in 'admin\f_admin.pas' {AdminForm},
  f_proxy in '..\misc\f_proxy.pas' {ProxyForm},
  f_gremium_task in 'Gremium\f_gremium_task.pas' {GremiumTaskForm},
  u_dataset_to_list in '..\misc\u_dataset_to_list.pas',
  f_task_delete in 'Task\f_task_delete.pas' {TaskDeleteForm},
  fr_tasklist_delete in 'Task\fr_tasklist_delete.pas' {UnusedTaskListFrame: TFrame},
  f_correctForm in 'nhunspell\f_correctForm.pas' {CorrectForm},
  f_select_dictinonary in 'nhunspell\f_select_dictinonary.pas' {SelectDictionaryForm},
  NHunspell in 'nhunspell\NHunspell.pas',
  NHunXml in 'nhunspell\NHunXml.pas',
  PasZip in 'nhunspell\PasZip.pas',
  u_SpellChecker in 'nhunspell\u_SpellChecker.pas',
  f_connect_form2 in 'nhunspell\f_connect_form2.pas' {FullCorrectForm},
  f_task_assigment in 'TaskEditor\f_task_assigment.pas' {TaskAssignmentForm},
  fr_textblock in 'TextBlock\fr_textblock.pas' {TextBlockFrame: TFrame},
  fr_editForm in 'misc\fr_editForm.pas' {EditFrame: TFrame},
  Vcl.Themes,
  Vcl.Styles,
  i_plugin in '..\Plugin\i_plugin.pas',
  u_pluginManager in '..\Plugin\Manager\u_pluginManager.pas',
  u_ForceClose in '..\misc\u_ForceClose.pas',
  f_passwd in '..\misc\f_passwd.pas' {PassWdform},
  u_ICrypt in '..\misc\u_ICrypt.pas',
  u_PluginData in '..\Plugin\Manager\u_PluginData.pas',
  u_IWindowHandler in '..\misc\u_IWindowHandler.pas',
  f_pluginAdmin in 'admin\f_pluginAdmin.pas' {PluginAdmin},
  xsd_TaskData in '..\misc\xsd_TaskData.pas',
  m_taskimporter in 'Task\m_taskimporter.pas' {TaskImporterMod: TDataModule},
  u_template in 'Task\u_template.pas',
  f_task_import in 'Task\f_task_import.pas' {TaskImportForm},
  fr_base in '..\misc\fr_base.pas' {BaseFrame: TFrame},
  f_mail in 'mail\f_mail.pas' {Mailform},
  m_mail in '..\misc\m_mail.pas' {MailMod: TDataModule},
  f_mail_imap in 'mail\f_mail_imap.pas' {MailimapConfigForm},
  f_mail_client in 'mail\f_mail_client.pas' {MailClientForm},
  fr_mails in 'mail\MailFrame\fr_mails.pas' {MailFrame: TFrame},
  u_TMail in 'mail\MailFrame\u_TMail.pas',
  u_mail_decoder in '..\misc\u_mail_decoder.pas',
  f_kategorie in 'mail\f_kategorie.pas' {KategorieForm},
  fr_files_to_delete in 'File\fr_files_to_delete.pas' {FilesToDeleteFrame: TFrame},
  u_meeting_status in '..\misc\u_meeting_status.pas';

{$R *.res}

begin
{$IFDEF DEBUG}
  CodeSite.Enabled := True;
  CodeSite.Clear;
{$ELSE}
  CodeSite.Enabled := False;
{$ENDIF}

{$ifdef RELEASE}
  JclAppInstances.CheckSingleInstance;
{$else}
  ReportMemoryLeaksOnShutdown := true;
{$endif}

  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.DefaultFont.Size  := 10;

  TStyleManager.TrySetStyle('Sapphire Kamri');
  Application.CreateForm(TGM, GM);
  Application.CreateForm(THttpMod, HttpMod);
  Application.CreateForm(TWindowHandler, WindowHandler);
  Application.CreateForm(TBookMarkHandler, BookMarkHandler);
  Application.CreateForm(TTemplateCacheMod, TemplateCacheMod);
  Application.CreateForm(TFileCacheMod, FileCacheMod);
  Application.CreateForm(TCryptMod, CryptMod);
  Application.CreateForm(TMainForm, MainForm);
  try
    Application.Run;
  except

  end;
end.
